# Return a boolean indicating if the targetsum can be generated by the numbers 
# in the array numbers. Assume all numbers in array are positive and you can 
# reuse the numbers as many times as you wish.

# let n = len(numbers) and m = targetsum
# O(n^m) in time and O(m) in space before memoisation


def cansum(targetsum, numbers):
    if targetsum == 0: return True
    
    for num in numbers:
        if targetsum >= num:
            remainder = targetsum - num
            if cansum(remainder, numbers) == True: return True
    
    return False


print(cansum(7,[5,3,4,7]))